#ifndef CPP_12784_READABILITY_REDUNDANT_FUNCTION_PTR_DEREFERENCE_H
#define CPP_12784_READABILITY_REDUNDANT_FUNCTION_PTR_DEREFERENCE_H

namespace readability::redundant_function_ptr_dereference {
void check();
} // namespace readability::redundant_function_ptr_dereference

#endif // CPP_12784_READABILITY_REDUNDANT_FUNCTION_PTR_DEREFERENCE_H
